### ISSUE TITLE
workspace build does not finish properly

### ISSUE THREAD

**Issue by ulricheck** [Ubitrack/ubitrack_release_tools#1]
after cleaning all files and then running:

doit workspace=True on a linux ubuntu 18.04 WS the workspace build is running (maybe even complete), but the comand fails with:
```
Using lockfile: '/home/netlabs/mydeps/recipies/ubitrack_release_tools/build/meta/../../install//conan.lock'
Using cached profile from lockfile
TaskError - taskid:package_worker_gen:package_worker_workspace_build
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/netlabs/mydeps/recipies/ubitrack_release_tools/dodo.py", line 381, in build_workspace
    result = conan_api.workspace_install(build_folder, options=build_parameter, install_folder=installFolder)
  File "/home/netlabs/mydeps/recipies/ubitrack_release_tools/workspace/ubitrackWorkspace.py", line 119, in workspace_install
    workspace.build(install_folder, deps_graph, self._user_io.out,self._hook_manager, self._graph_manager)
  File "/home/netlabs/mydeps/recipies/ubitrack_release_tools/workspace/ubitrackWorkspace.py", line 157, in build
    _build.build(graph_manager,hook_mangaer,conanFilePath,src,build, install_folder, build)
  File "/home/netlabs/.local/lib/python3.6/site-packages/conans/client/cmd/build.py", line 22, in build
    deps_info_required=True, test=test)
  File "/home/netlabs/.local/lib/python3.6/site-packages/conans/client/graph/graph_manager.py", line 87, in load_consumer_conanfile
    lock_python_requires=lock_python_requires)
  File "/home/netlabs/.local/lib/python3.6/site-packages/conans/client/loader.py", line 121, in load_consumer
    raise ConanException("Package recipe name %s!=%s" % (name, conanfile_class.name))
conans.errors.ConanException: Package recipe name meta!=ubitrack

```

**Comment by FriederPankratz** [comment]
bug should be fixed.
requires conan 1.18.0 (current release)

**Comment by ulricheck** [comment]
works for me
